//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eliseproweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailBills = new HashSet<DetailBill>();
        }
    
        public int ID { get; set; }
        public string codeProduct { get; set; }
        public string nameProduct { get; set; }
        public string descriptionProduct { get; set; }
        public Nullable<int> quantityProductInput { get; set; }
        public Nullable<double> priceProductInput { get; set; }
        public string sizeProuct { get; set; }
        public string genderUse { get; set; }
        public Nullable<int> IDStyle { get; set; }
        public string imageProduct1 { get; set; }
        public string imageProduct2 { get; set; }
        public string imageProduct3 { get; set; }
        public string imageProduct4 { get; set; }
        public string imageProduct5 { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
        public virtual Style Style { get; set; }
    }
}
