//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hocsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailBill
    {
        public int ID { get; set; }
        public int IDBill { get; set; }
        public string CodeProduct { get; set; }
        public Nullable<int> QuantityProduct { get; set; }
        public Nullable<double> PriceProductBuying { get; set; }
        public Nullable<double> TotalMoney { get; set; }
    
        public virtual tblBill tblBill { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
